Added Register User Pages
KanaoReeves/KeanuFromFront pull request #16
Opened 2017-03-07 18:59 UTC by kevinburnside

Added register pages along with paymentinfo pages. 
data is being passed from register to payment pages.
Still need to create the data property to send info to the backend.

2017-03-07 21:31 UTC, aagavin requested changes

2017-03-07 21:31 UTC, aagavin commented on Keanu/src/pages/login/login.html
> +  <div padding>
Is it possible to make this button less prominent or smaller?
Also can we add a message that says something like "don't have an account? Register here"

2017-03-07 21:31 UTC, aagavin commented on Keanu/src/pages/paymentInfo/paymentInfo.html
> +</ion-content>
new line at end of file needed

2017-03-07 21:31 UTC, aagavin commented on Keanu/src/pages/register/register.html
> +</ion-content>
new line at end of file needed

2017-03-09 15:38 UTC, MavOmidK approved these changes
Looks good, all works

2017-03-09 15:39 UTC, aagavin approved these changes

2017-03-09 15:39 UTC, merged